scratch-org-def: config/project-scratch-def.json
assign-permset: true
permset-name: nto
run-apex-tests: false
delete-scratch-org: false
show-scratch-org-url: true
data-plans:
  - ./data/sample-data-Merchandise__c-plan.json
